/camera1/camera1:
  ros__parameters:
    color_width: 640
    color_height: 480
    color_fps: 30
    color_frame_id: "color_frame1"
    color_optical_frame_id: "color_optical_frame1"
    enable_color: true
    ir_width: 640
    ir_height: 480
    ir_fps: 30
    ir_frame_id: "ir_frame1"
    ir_optical_frame_id: "ir_optical_frame1"
    enable_ir: false
    depth_width: 640
    depth_height: 480
    depth_fps: 25
    depth_frame_id: "depth_frame1"
    depth_optical_frame_id: "depth_optical_frame1"
    enable_depth: true
    publish_tf: true
    tf_publish_rate: 10.0
    publish_rgb_point_cloud: true
    wait_for_device_timeout: 120.0
    reconnect_timeout: 6.0
    d2c_mode: "hw"
    serial_number: "BY19810004G"
    camera_link_frame_id: "camera1_link"
    ob_log_level: "none"
