services:
  orbbec:
    build:
      dockerfile: Dockerfile
    command: ros2 launch orbbec_camera femto_bolt.launch.py
    restart: unless-stopped
    privileged: true
    network_mode: host
    volumes:
      - /dev:/dev
