/**:
  ros__parameters:
    color_width: 640
    color_height: 480
    color_fps: 30
    color_frame_id: "color_frame"
    color_optical_frame_id: "color_optical_frame"
    enable_color: true
    ir_width: 640
    ir_height: 480
    ir_fps: 30
    ir_frame_id: "ir_frame"
    ir_optical_frame_id: "ir_optical_frame"
    enable_ir: false
    depth_width: 640
    depth_height: 480
    depth_fps: 25
    depth_frame_id: "depth_frame"
    depth_optical_frame_id: "depth_optical_frame"
    enable_depth: true
    publish_tf: true
    align_depth: true
    tf_publish_rate: 10.0
    publish_rgb_point_cloud : true
    d2c_mode : "hw"
